package CMS.sys.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.geo.Point;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

/**
 * Entity class representing a Contact in the system.
 * This class is mapped to the "contacts" collection in MongoDB.
 * 
 * Design Considerations:
 * - Uses Lombok annotations to reduce boilerplate code
 * - Indexed fields (email, mobileNumber) for faster queries
 * - Audit fields (createdAt, updatedAt) for tracking changes
 * - Builder pattern for flexible object creation
 * - Ready for future enhancements (groups, multiple phones/emails, etc.)
 * 
 * @author Contact Management System
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "contacts")
public class Contact {

    /**
     * Unique identifier for the contact.
     * Auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * First name of the contact.
     * Required field.
     */
    private String firstName;

    /**
     * Last name of the contact.
     * Required field.
     */
    private String lastName;

    /**
     * Nickname or preferred name of the contact.
     * Optional field.
     */
    private String nickname;

    /**
     * Primary mobile number of the contact.
     * Indexed for faster lookups.
     * Future: Can be extended to support multiple phone numbers.
     */
    @Indexed(unique = true, sparse = true)
    private String mobileNumber;

    @Indexed(unique = true, sparse = true)
    private String email;

    private String company;

    private String designation;

    private String address;

    private String city;

    private String state;

    private String country;

    private String notes;

    private org.springframework.data.geo.Point location;

    private java.util.List<String> groups;

    private java.util.List<PhoneNumber> phoneNumbers;

    private java.util.List<EmailAddress> emailAddresses;

    @Schema(description = "URL of profile photo", example = "/uploads/profile-photos/contact-123.jpg")
    private String profilePhotoUrl;

    private java.time.LocalDate birthday;

    @Builder.Default
    private Boolean favorite = false;

    /**
     * Timestamp when the contact was created.
     * Automatically set by Spring Data MongoDB.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp when the contact was last updated.
     * Automatically updated by Spring Data MongoDB.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;

    // Future fields that can be added:
    // - private String userId; // For multi-user support
    // - private List<String> tags; // Custom tags
    // - private Map<String, String> customFields; // Extensible fields
}
